CIS_DYNAMODB_TABLE: cis-stream-prod-and-idv-IdentityVaultUsers-LMGGZ2XE8K6F
CIS_ARN_MASTER_KEY: arn:aws:kms:us-west-2:371522382791:key/adef50ad-2846-46df-b783-1c8f35e858cb
CIS_STREAM_ARN: arn:aws:kinesis:us-west-2:371522382791:stream/cis-stream-prod-and-idv-CISInputStream-1R29T8G6ZQTQ5
CIS_KINESIS_STREAM_NAME: cis-stream-prod-and-idv-CISInputStream-1R29T8G6ZQTQ5
CIS_IAM_ROLE_ARN: arn:aws:iam::371522382791:role/CISPublisherRole
CIS_PUBLISHER_NAME: ldap
CIS_IAM_ROLE_SESSION_NAME: production_ldap_client
CIS_LAMBDA_VALIDATOR_ARN: arn:aws:lambda:us-west-2:371522382791:function:cis_functions_prod_latest_validator
CIS_PERSON_API_URL: person-api.sso.mozilla.com
CIS_PERSON_API_AUDIENCE: https://person-api.sso.mozilla.com
CIS_PERSON_API_VERSION: v1
CIS_OAUTH2_DOMAIN: auth.mozilla.auth0.com
CIS_LOGGING_OUTPUT: cloudwatch
CIS_LOGGING_LEVEL: DEBUG
CIS_CLOUDWATCH_LOG_GROUP: production
CIS_LDAP_DIFF_BUCKET: cis-ldap2s3-publisher-data
CIS_LDAP_S3_REGION: us-east-1
CIS_LDAP_JSON_FILE: ldap.json.xz
LDAP_NAMESPACE: Mozilla-LDAP
SIGNING_KEY_ARN: arn:aws:kms:us-west-2:371522382791:alias/pykmssig
